### ISSUE TITLE
Not compatible with blender 3+

### ISSUE THREAD

**Issue by anon437** [supertuxkart/stk-blender#16]
Due to the deprecation of object proxies in favor of "library overrides" starting in blender 3+, exporting fails with error "Attribute Error: obj has no attribute proxy."

**Comment by blender-girl** [comment]
Can I use the blender exporter with Blender 3.4 when following installation instructions?

**Comment by Benau** [comment]
Probably work if no library objects are used

**Comment by blender-girl** [comment]
> Probably work if no library objects are used

I'm a beginner: what are library objects?

**Comment by qwertychouskie** [comment]
https://supertuxkart.net/Making_Tracks

**Comment by 3risian** [comment]
@blender-girl Did it work on Blender 3.4? Or did you use an older version?

Library objects are pre-made objects like trees and buildings that you can import from the SuperTuxKart Media Repository. Blender can link to these existing objects instead of your project just remaking it. This also means that if an artist improves the library object (like fixing an issue or adding detail), it improves the one in all the tracks that link to it, without anyone needing to update all of them.

See also: https://supertuxkart.net/Making_Tracks:_Decorations#decorations-from-the-media-repository

**Comment by blender-girl** [comment]
I gave up sorry...
Couldn't even download from subversion because I don't know anything about it.
The art contributions to STK are miles away for artists since they first need to know how all the developers tools work.
So most of them give up (like me)
